server:
  port: 8101
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        namespace: xxgo
        group: xxgo
        shared-configs[0]:
          data-id: dev.properties
          group: xxgo
          refresh: false
      discovery:
        server-addr: localhost:8848
#            discovery:
#                namespace: xxgo
#                group: xxgo
feign:
  hystrix:
    enabled: true